input {
  kafka {
    bootstrap_servers => "kafka:29092"
    topics => ["ticket-logs"]
    codec => json
    client_id => "logstash_ticket_consumer"
  }
}

output {
  opensearch {
    hosts => ["http://opensearch:9200"]
    index => "ticket-backend-logs-%{+YYYY.MM.dd}"
    ssl => false
    ssl_certificate_verification => false
  }
  stdout { codec => rubydebug }
}