spring.application.name=ticket-management-system
spring.datasource.url=jdbc:postgresql://localhost:5433/ticketdb
spring.datasource.username=ticketuser
spring.datasource.password=ticketpass

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.jpa.open-in-view=false

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# --- MULTIPART (FILE UPLOAD) CONFIGURATION ---
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

app.storage.upload-dir=uploads/tickets