spring.application.name=ticket-management-system
spring.datasource.url=jdbc:postgresql://localhost:5433/ticketdb
spring.datasource.username=ticketuser
spring.datasource.password=ticketpass

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.jpa.open-in-view=false

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration